blank_issues_enabled: false
contact_links:
  - name: "Página de ayuda de 'Control de Agua'"
    url: https://ControlDeAgua.github.io/ControlDeAgua-docs/troubleshooting
    about: "Lee este documento antes de reportar algún error."
